---
title: Royal College of Art Poster Archive
description: This site is an archive of the Royal College of Art's posters.
url: https://jacobcharleswilson.com/rca-poster-archive
enforce_ssl: jacobcharleswilson.com
cdn:
  url: https://s3.eu-west-2.amazonaws.com/rca-poster-archive/images/
email: example@example.org
twitter:
  username: "exampleTW"
instagram:
  username: "exampleIG"
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
