---
title: Royal College of Art Poster Archive
description: Example long description NA is a database of collected + referenced images. This data has been sourced from a 55x135cm receptacle placed 29 steps from entrance to Tesco (E9 6ND). These objects have been displaced from their original intended course, rejected and placed in the new container
url: https://jacobcharleswilson.com/rca-poster-archive
enforce_ssl: jacobcharleswilson.com
cdn:
  url: https://s3.eu-west-2.amazonaws.com/rca-poster-archive/images/
email: example@example.org
twitter:
  username: "exampleTW"
instagram:
  username: "exampleIG"
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-sitemap
